//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MegabiteEntityLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CafeteriaEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CafeteriaEntities1 object using the connection string found in the 'CafeteriaEntities1' section of the application configuration file.
        /// </summary>
        public CafeteriaEntities1() : base("name=CafeteriaEntities1", "CafeteriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CafeteriaEntities1 object.
        /// </summary>
        public CafeteriaEntities1(string connectionString) : base(connectionString, "CafeteriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CafeteriaEntities1 object.
        /// </summary>
        public CafeteriaEntities1(EntityConnection connection) : base(connection, "CafeteriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Card_Details> Card_Details
        {
            get
            {
                if ((_Card_Details == null))
                {
                    _Card_Details = base.CreateObjectSet<Card_Details>("Card_Details");
                }
                return _Card_Details;
            }
        }
        private ObjectSet<Card_Details> _Card_Details;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Card_Details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCard_Details(Card_Details card_Details)
        {
            base.AddObject("Card_Details", card_Details);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CafeteriaModel1", Name="Card_Details")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Card_Details : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Card_Details object.
        /// </summary>
        /// <param name="card_Detail_ID">Initial value of the Card_Detail_ID property.</param>
        public static Card_Details CreateCard_Details(global::System.Int64 card_Detail_ID)
        {
            Card_Details card_Details = new Card_Details();
            card_Details.Card_Detail_ID = card_Detail_ID;
            return card_Details;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Card_Detail_ID
        {
            get
            {
                return _Card_Detail_ID;
            }
            set
            {
                if (_Card_Detail_ID != value)
                {
                    OnCard_Detail_IDChanging(value);
                    ReportPropertyChanging("Card_Detail_ID");
                    _Card_Detail_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Card_Detail_ID");
                    OnCard_Detail_IDChanged();
                }
            }
        }
        private global::System.Int64 _Card_Detail_ID;
        partial void OnCard_Detail_IDChanging(global::System.Int64 value);
        partial void OnCard_Detail_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Card_ID
        {
            get
            {
                return _Card_ID;
            }
            set
            {
                OnCard_IDChanging(value);
                ReportPropertyChanging("Card_ID");
                _Card_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Card_ID");
                OnCard_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _Card_ID;
        partial void OnCard_IDChanging(Nullable<global::System.Int64> value);
        partial void OnCard_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Amount_Loaded
        {
            get
            {
                return _Amount_Loaded;
            }
            set
            {
                OnAmount_LoadedChanging(value);
                ReportPropertyChanging("Amount_Loaded");
                _Amount_Loaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount_Loaded");
                OnAmount_LoadedChanged();
            }
        }
        private Nullable<global::System.Double> _Amount_Loaded;
        partial void OnAmount_LoadedChanging(Nullable<global::System.Double> value);
        partial void OnAmount_LoadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Loaded_Datetime
        {
            get
            {
                return _Loaded_Datetime;
            }
            set
            {
                OnLoaded_DatetimeChanging(value);
                ReportPropertyChanging("Loaded_Datetime");
                _Loaded_Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Loaded_Datetime");
                OnLoaded_DatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Loaded_Datetime;
        partial void OnLoaded_DatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLoaded_DatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Loaded_By
        {
            get
            {
                return _Loaded_By;
            }
            set
            {
                OnLoaded_ByChanging(value);
                ReportPropertyChanging("Loaded_By");
                _Loaded_By = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Loaded_By");
                OnLoaded_ByChanged();
            }
        }
        private Nullable<global::System.Int32> _Loaded_By;
        partial void OnLoaded_ByChanging(Nullable<global::System.Int32> value);
        partial void OnLoaded_ByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Transafered_From_Card
        {
            get
            {
                return _Transafered_From_Card;
            }
            set
            {
                OnTransafered_From_CardChanging(value);
                ReportPropertyChanging("Transafered_From_Card");
                _Transafered_From_Card = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Transafered_From_Card");
                OnTransafered_From_CardChanged();
            }
        }
        private Nullable<global::System.Int64> _Transafered_From_Card;
        partial void OnTransafered_From_CardChanging(Nullable<global::System.Int64> value);
        partial void OnTransafered_From_CardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RFID_No
        {
            get
            {
                return _RFID_No;
            }
            set
            {
                OnRFID_NoChanging(value);
                ReportPropertyChanging("RFID_No");
                _RFID_No = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RFID_No");
                OnRFID_NoChanged();
            }
        }
        private global::System.String _RFID_No;
        partial void OnRFID_NoChanging(global::System.String value);
        partial void OnRFID_NoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Employee_ID
        {
            get
            {
                return _Employee_ID;
            }
            set
            {
                OnEmployee_IDChanging(value);
                ReportPropertyChanging("Employee_ID");
                _Employee_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Employee_ID");
                OnEmployee_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Employee_ID;
        partial void OnEmployee_IDChanging(Nullable<global::System.Int32> value);
        partial void OnEmployee_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Closing_Balance
        {
            get
            {
                return _Closing_Balance;
            }
            set
            {
                OnClosing_BalanceChanging(value);
                ReportPropertyChanging("Closing_Balance");
                _Closing_Balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Closing_Balance");
                OnClosing_BalanceChanged();
            }
        }
        private Nullable<global::System.Double> _Closing_Balance;
        partial void OnClosing_BalanceChanging(Nullable<global::System.Double> value);
        partial void OnClosing_BalanceChanged();

        #endregion

    
    }

    #endregion

    
}
